config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :conteos

  root to: "conteos#index"

end

app/models/conteo.rb
class Conteo < ActiveRecord::Base
  validates :loc_core, :loc_total, :dia, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def admin_required
    redirect_to new_user_session_path unless current_user.try(:email) == 'fcalatayud@gmail.com'
  end
end

app/controllers/conteos_controller.rb
class ConteosController < ApplicationController
  before_action :admin_required, except: :index

  def index
    @conteos = Conteo.order(:dia)
  end

  def new
    @conteo = Conteo.new
  end

  def create
    @conteo = Conteo.new(params_conteo)
    @conteo.save or return render('new')
    redirect_to conteos_path
  end

  def edit
    @conteo = Conteo.find(params[:id])
  end

  def update
    @conteo = Conteo.find(params[:id])
    @conteo.update_attributes(params_conteo) or return render('edit')
    redirect_to conteos_path
  end

  def destroy
    Conteo.find(params[:id]).destroy
    redirect_to conteos_path
  end

  private

  def params_conteo
    params.require(:conteo).permit(:dia, :loc_core, :loc_total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conteos_helper.rb
module ConteosHelper
end

app/views/conteos/_form.html.haml
= simple_form_for @conteo do |f|
  = f.input :dia
  = f.input :loc_core
  = f.input :loc_total
  = f.button :submit

app/views/conteos/edit.html.haml
%h1 Editar conteo #{l(@conteo.dia, format: :long)}

= render 'form'

app/views/conteos/form.html.haml
= simple_form_for @conteo do |f|
  = f.input :dia
  = f.input :loc_core
  = f.input :loc_total
  = f.button :submit

app/views/conteos/index.html.haml
%h1 Conteos

= link_to 'Nuevo conteo', new_conteo_path

%table
  %tr
    %th= Conteo.human_attribute_name(:dia)
    %th= Conteo.human_attribute_name(:loc_core)
    %th= Conteo.human_attribute_name(:loc_total)
    %th Acciones
  - @conteos.each do |conteo|
    %tr
      %td= l(conteo.dia)
      %td= conteo.loc_core
      %td= conteo.loc_total
      %td
        = link_to 'Editar', edit_conteo_path(conteo)
        = link_to 'Borrar', conteo_path(conteo), method: :delete

app/views/conteos/new.html.haml
%h1 Nuevo conteo

= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KpiCore
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    .flota-der
      - if user_signed_in?
        = current_user.email
        = link_to 'Logout', destroy_user_session_path, method: :delete
      - else
        = link_to 'Login', new_user_session_path
        = link_to 'Registro', new_user_registration_path
    = yield